mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from polls.views import login_view, logout_view

urlpatterns = [

    path('admin/', admin.site.urls),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('polls/', include('polls.urls')),

]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('create_quest_with_choice/', views.create_quest_with_choice, name='create_quest_with_choice'),

   ]

polls/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, default=2, on_delete=models.CASCADE)

    class Meta:
        ordering = ('-pub_date',)

    def __str__(self):
        return self.question_text



class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/forms.py
from django import forms
from .models import Question, Choice
from django.forms import modelformset_factory
from django.contrib.auth import authenticate, get_user_model


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ('question_text',)


class QuestionModelForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ('question_text',)
        labels = {
            'question_text': 'Question',
            }
        widgets = {
            'question_text': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Enter question here'
                }),

        }


QuestionModelFormset = modelformset_factory(
    Question,
    fields=('question_text', ),
    extra=1,
    widgets={
        'question_text': forms.Textarea(attrs={
            'class': 'form-control',
            'placeholder': 'Enter Question here'
            }),
    }
)

ChoiceFormset = modelformset_factory(
    Choice,
    fields=('choice_text', ),
    extra=1,
    widgets={'choice_text': forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Enter choice here'
        })
    }
)


class ChoiceForm(forms.ModelForm):
    class Meta:
        model = Choice
        fields = ('choice_text', )


User = get_user_model()


class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        if username and password:
            user = authenticate(username=username, password=password)
            if not user:
                raise forms.ValidationError("This user does not exist")
            if not user.check_password(password):
                raise forms.ValidationError("Incorrect Password")
            if not user.is_active:
                raise forms.ValidationError("This user is no longer active")
        return super(UserLoginForm, self).clean(*args, **kwargs)

polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render, get_object_or_404, redirect
from .forms import QuestionModelForm, ChoiceFormset, UserLoginForm
from .models import Question, Choice
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth import authenticate, login, logout


def index(request):
    polls = Question.objects.order_by('-pub_date')
    paginator = Paginator(polls, 3)  # 3 posts in each page
    page = request.GET.get('page')
    try:
        latest_question_list = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        latest_question_list = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        latest_question_list = paginator.page(paginator.num_pages)
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', {'page': page, 'latest_question_list': latest_question_list})
    #return render(request, 'polls/index.html', context)


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))



def create_quest_with_choice(request):
    template_name = 'polls/create_quest_with_choice.html'
    if request.method == 'GET':
        questionform = QuestionModelForm(request.GET or None)
        formset = ChoiceFormset(queryset=Choice.objects.none())
    elif request.method == 'POST':
        questionform = QuestionModelForm(request.POST)
        formset = ChoiceFormset(request.POST)
        if questionform.is_valid() and formset.is_valid():
            # first save this book, as its reference will be used in `Author`
            question = questionform.save(commit=False)
            question.author = request.user
            question.save()
            for form in formset:
                # so that `book` instance can be attached.
               # print("choice text ", form.choice_text)
                choice = form.save(commit=False)
                choice.question = question
                choice.save()
            return redirect('polls:index')
    return render(request, template_name, {
        'questionform': questionform,
        'formset': formset,
    })


def login_view(request):
    title = "Login"
    form = UserLoginForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        user = authenticate(username=username, password=password)
        login(request, user)
        return redirect('polls:index')
    return render(request, 'registration/login_form.html', {'form': form, 'title': title})



def logout_view(request):
    logout(request)
    return redirect('polls:index')

polls/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <style type="text/css">
        .spacer{
            margin-top:25px;
        }
    </style>
    {% block custom_css %}{% endblock %}
    <title>Django Poll App</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Django Poll App</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="nav navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'polls:index' %}">Home </a>

                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                            <li class="nav-item active"><a class="nav-link" href="{% url 'polls:create_quest_with_choice' %}">Create new poll</a></li>
                            <li class="nav-item active"><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>

                {% else %}
                            <li class="nav-item active"><a class="nav-link" href="{% url 'login' %}">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class="container">
        <div class="row spacer"></div>
        <div class="row offset-2">
            <div class="col-12">
                {% block container %}
                {% endblock %}
            </div>
        </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <link rel=”stylesheet” href=”//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css”>
    <link rel="stylesheet" href="/resources/demos/style.css">
    <script src=”https://code.jquery.com/jquery-1.12.4.js”></script>
    <script src=”https://code.jquery.com/ui/1.12.1/jquery-ui.js”></script>
    {% block custom_js %}{% endblock %}
</body>

</html>

polls/templates/polls/create_quest_with_choice.html
{% extends "base.html" %}

{% block container %}
{% if heading %}
<h3>{{heading}}</h3>
{% endif %}
<form class="form-horizontal" method="POST" action="">
    {% csrf_token %}
<div class="row spacer">
    <div class="col-2">
        <label>{{questionform.question_text.label}}</label>
    </div>
    <div class="col-4">
        <div class="form-group">
            <table>
                <tr><td>{{questionform.question_text}}</td></tr>

            </table>
        </div>

    </div>
</div>

{{ formset.management_form }}
{% for form in formset %}
<div class="row form-row spacer">
    <div class="col-2">
        <label>{{form.choice_text.label}}</label>
    </div>
    <div class="col-4">
        <div class="input-group">
            {{form.choice_text}}
            <div class="input-group-append">
                <button class="btn btn-success add-form-row">+</button>
            </div>
        </div>
    </div>
</div>
{% endfor %}
<div class="row spacer">
    <div class="col-4 offset-2">
        <button type="submit" class="btn btn-default">Create</button>
    </div>
</div>
</form>
{% endblock %}

{% block custom_js %}

<script type="text/javascript">
function updateElementIndex(el, prefix, ndx) {
    var id_regex = new RegExp('(' + prefix + '-\\d+)');
    var replacement = prefix + '-' + ndx;
    if ($(el).attr("for")) $(el).attr("for", $(el).attr("for").replace(id_regex, replacement));
    if (el.id) el.id = el.id.replace(id_regex, replacement);
    if (el.name) el.name = el.name.replace(id_regex, replacement);
}
function cloneMore(selector, prefix) {
    var newElement = $(selector).clone(true);
    var total = $('#id_' + prefix + '-TOTAL_FORMS').val();

    newElement.find(':input').each(function() {
        var name = $(this).attr('choice_text')
        if(name) {
            name = name.replace('-' + (total-1) + '-', '-' + total + '-');
            var id = 'id_' + name;

            $(this).attr({'choice_text': name, 'id': id}).val('').removeAttr('checked');

        }
        updateElementIndex(this, prefix, total);
    });
    total++;
    $('#id_' + prefix + '-TOTAL_FORMS').val(total);
    $(selector).after(newElement);
    var conditionRow = $('.form-row:not(:last)');
    conditionRow.find('.btn.add-form-row')
    .removeClass('btn-success').addClass('btn-danger')
    .removeClass('add-form-row').addClass('remove-form-row')
    .html('-');
    return false;
}
function deleteForm(prefix, btn) {
    var total = parseInt($('#id_' + prefix + '-TOTAL_FORMS').val());
    if (total > 1){
        btn.closest('.form-row').remove();
        var forms = $('.form-row');
        $('#id_' + prefix + '-TOTAL_FORMS').val(forms.length);
        for (var i=0, formCount=forms.length; i<formCount; i++) {
            $(forms.get(i)).find(':input').each(function() {
                updateElementIndex(this, prefix, i);
            });
        }
    }
    return false;
}
$(document).on('click', '.add-form-row', function(e){
    e.preventDefault();
    cloneMore('.form-row:last', 'form');
    return false;
});
$(document).on('click', '.remove-form-row', function(e){
    e.preventDefault();
    deleteForm('form', $(this));
    return false;
});


</script>

{% endblock %}

polls/templates/polls/detail.html
{% extends 'base.html' %}

{% block title %}{{ question.question_text }}{% endblock %}

{% block container %}
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<p class="date">
    Published {{ question.pub_date }}
  </p>
    {{ question.body|linebreaks }}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}

    <div class="radio">

        <p><label for="choice{{ forloop.counter }}">
            <input type="radio"  name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            {{ choice.choice_text }}</label></p>
    </div>
<br/>
{% endfor %}
<br/>

<input type="submit" value="Vote" class="btn btn-default">
</form>

{% endblock %}

polls/templates/polls/index.html
{% extends 'base.html' %}

{% block title %}Polls{% endblock %}

{% block container %}
    <h1>Polls</h1>

{% if latest_question_list %}

    {% for question in latest_question_list %}

      <table>
        <tr>
            <td colspan="2"><h3>{{ question.question_text }}</h3></td>
        </tr>
            <tr>
                <td><p class="date"> Published {{ question.pub_date }}</p></td>
                 <td><p><a class="nav-link" href="{% url 'polls:detail' question.id %}">Vote your choice</a></p></td>
                 <td><p><a class="nav-link" href="{% url 'polls:results' question.id %}">View Result</a></p></td>
            </tr>
      </table>


        {{ question.body|truncatewords:30|linebreaks }}
    {% endfor %}

{% else %}
    <p>No polls are available.</p>
{% endif %}
 {% include "polls/pagination.html" with page=latest_question_list %}
{% endblock %}

polls/templates/polls/pagination.html
<div class="pagination">
  <span class="step-links">
    {% if page.has_previous %}
      <a href="?page={{ page.previous_page_number }}">Previous</a>
    {% endif %}
    <span class="current">
      Page {{ page.number }} of {{ page.paginator.num_pages }}.
    </span>
      {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a>
      {% endif %}
  </span>
</div>

polls/templates/polls/results.html
{% extends 'base.html' %}


{% block container %}
    <h1>Poll Results</h1>
     <div >
     <span><h3>{{ question.question_text }}</h3>
         <a class="nav-link" href="{% url 'polls:detail' question.id %}">Vote again?</a></span>
    </div>

<div >

<table class="table table-striped table-bordered"">
        <thead>
         <th>Choice</th>
         <th>Vote Count</th>
        </thead>
    <tbody>
{% for choice in question.choice_set.all %}

    <tr>
        <td>{{ choice.choice_text }}</td>
         <td>{{ choice.votes }}</td>
    </tr>
{% endfor %}
 </tbody>
    </table>

</div>

{% endblock %}